import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans, Work_Sans, Open_Sans } from "next/font/google";
import ToastProvider from "./components/common/Toast";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${notoSans.variable} ${workSans.variable} ${openSans.variable} h-screen overflow-hidden`}
    >
      <body className="h-screen overflow-hidden">
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
