import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans, Work_Sans, Open_Sans } from "next/font/google";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${notoSans.variable} ${workSans.variable} ${openSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
